[package]
name = "ascii-arts-generator-ufv-rust"
version = "0.1.0"
authors = ["Mateus Pinto da Silva <mateus.p.silva@ufv.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
